version: '3'
services:
  eureka-server1:
    image: eureka-server
    build: .
    ports:
      - 8001:8001
    environment:
      - spring.profiles.active=peer1

  eureka-server2:
      image: eureka-server
      build: .
      ports:
        - 8002:8002
      environment:
        - spring.profiles.active=peer2

  eureka-server3:
        image: eureka-server
        build: .
        ports:
          - 8003:8003
        environment:
          - spring.profiles.active=peer3